version: "3.8"

services:
  database:
    image: postgres:14-alpine
    container_name: barcode-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: barcode
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    #    volumes:
    #     - .:/app
    #      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@database/barcode
    depends_on:
      - database

volumes:
  postgres-data:
